"""
Brushed-DC motor simulation with RK4 integration, Stribeck friction, a thermal
model, and a properly reflected gearbox.

Physics (SI units, motor side):

    Electrical:  L * di/dt   = V - R * i - Ke * omega_m
    Mechanical:  J * domega_m/dt = Kt * i - b * omega_m - tau_friction - tau_load_m

  - omega_m is the *motor-shaft* (rotor) speed. For a brushed DC motor in SI
    units the back-EMF constant Ke equals the torque constant Kt; we keep them as
    separate fields so a non-ideal motor can be modelled, defaulting Ke = Kt.
  - tau_friction is the Coulomb + viscous + Stribeck friction torque from
    :mod:`robot_testbench.motor.friction`, with correct stiction handling.
  - tau_load_m is any external load torque referred to the *motor* shaft.

Gearbox convention (reduction ratio N = gear_ratio, output speed = motor speed / N):
  - State (current, omega, theta) is integrated on the MOTOR side.
  - A load attached at the OUTPUT with inertia J_out and constant/Coulomb torque
    tau_out reflects to the motor shaft as:
        J_reflected   = J_out / N**2
        tau_reflected = tau_out / (N * efficiency)
    so the rotor "feels" J_motor + J_out/N**2. This is the standard reflected-
    inertia relationship and is what makes a high reduction ratio dominate the
    effective inertia.
  - Back-EMF is generated by the motor speed (Ke * omega_m). Referred to the
    output shaft (omega_out = omega_m / N) the effective back-EMF constant is
    Ke * N -- i.e. it scales *with* the ratio, the dual of torque scaling.
  - Output torque delivered to the load = N * efficiency * (Kt * i).
  - ``get_state()`` and the (position, velocity) returned by ``step`` are
    OUTPUT-side quantities; ``current`` is the true motor winding current.

Determinism: ``step`` advances time purely by the supplied ``dt`` -- there is no
wall-clock (``time.time()``) dependence anywhere in the integration, so a given
input sequence always produces identical output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from .friction import FrictionParameters, friction_torque, is_stuck
from .integrators import rk4_step


@dataclass
class MotorParameters:
    """Brushed-DC motor parameters (motor-side / rotor values)."""

    inertia: float  # J, rotor inertia [kg.m^2]
    damping: float  # b, viscous damping [N.m.s/rad]
    torque_constant: float  # Kt [N.m/A]
    max_torque: float  # [N.m] (used for current clamping)
    max_speed: float  # [rad/s] (output-side speed clamp)
    resistance: float  # R [Ohm]
    inductance: float  # L [H]
    back_emf_constant: Optional[float] = None  # Ke [V.s/rad]; defaults to Kt (SI)
    thermal_mass: float = 0.1  # [J/K]  (heat capacity)
    thermal_resistance: float = 0.5  # [K/W]
    gear_ratio: float = 1.0  # N (reduction); output speed = motor speed / N
    gear_efficiency: float = 1.0  # eta in (0, 1]
    ambient_temp: float = 25.0  # [degC]
    max_temp: float = 100.0  # [degC]
    temp_coeff: float = 0.0039  # [1/degC] copper resistance tempco (reserved)
    # Friction model (Coulomb + viscous + Stribeck). Defaults to viscous-only so
    # that the closed-form steady-state validation (no Coulomb friction) holds.
    coulomb_torque: float = 0.0  # tau_c [N.m]
    static_torque: float = 0.0  # tau_s [N.m] break-away (>= tau_c)
    stribeck_velocity: float = 0.05  # omega_s [rad/s]

    @property
    def ke(self) -> float:
        """Back-EMF constant Ke; equals Kt for an ideal SI brushed-DC motor."""
        return self.torque_constant if self.back_emf_constant is None else self.back_emf_constant

    def friction_params(self) -> FrictionParameters:
        """Build the friction-model parameter set from the motor parameters."""
        return FrictionParameters(
            coulomb_torque=self.coulomb_torque,
            static_torque=max(self.static_torque, self.coulomb_torque),
            viscous_damping=self.damping,
            stribeck_velocity=self.stribeck_velocity,
        )


@dataclass
class PIDGains:
    """PID controller gains (kept for backward compatibility)."""

    kp: float
    ki: float
    kd: float


# State vector layout for RK4 integration (motor side):
#   x[0] = current i        [A]
#   x[1] = omega_m          [rad/s]  (motor shaft)
#   x[2] = theta_m          [rad]    (motor shaft)
_I, _W, _TH = 0, 1, 2


class MotorSimulator:
    """Brushed-DC motor simulator (RK4 + Stribeck friction + reflected gearbox)."""

    def __init__(self, params: MotorParameters):
        self.params = params
        # Internal state is motor-side.
        self.position = 0.0  # output-side angle [rad]  (exposed)
        self.velocity = 0.0  # output-side speed [rad/s] (exposed)
        self.current = 0.0  # motor winding current [A]
        self._theta_m = 0.0  # motor-side angle [rad]
        self._omega_m = 0.0  # motor-side speed [rad/s]
        self.temperature = params.ambient_temp  # [degC]
        self._sim_time = 0.0  # accumulated sim time [s]

    # ------------------------------------------------------------------ helpers
    def _current_limit(self) -> float:
        return self.params.max_torque / self.params.torque_constant

    def _motor_speed_limit(self) -> float:
        """Motor-side speed clamp (max output speed referred to the motor)."""
        return self.params.max_speed * self.params.gear_ratio

    def _state_derivative(self, voltage: float, load_torque_motor: float):
        """Return a closure computing dx/dt for the RK4 step.

        Inputs (voltage, reflected load torque) are held constant over the step.
        Friction is evaluated using the *current* electromagnetic torque to drive
        the stiction logic; this is a first-order-accurate treatment of the
        non-smooth friction term, which is standard for stick-slip simulation.
        """
        p = self.params
        fp = p.friction_params()

        def f(x: np.ndarray) -> np.ndarray:
            i, omega = x[_I], x[_W]
            # Electrical: L di/dt = V - R i - Ke omega
            di_dt = (voltage - p.resistance * i - p.ke * omega) / p.inductance
            # Net non-friction torque on the rotor (drives stiction decision).
            tau_em = p.torque_constant * i
            applied = tau_em - load_torque_motor
            tau_f = friction_torque(omega, applied, fp)
            domega_dt = (tau_em - load_torque_motor - tau_f) / p.inertia
            dtheta_dt = omega
            return np.array([di_dt, domega_dt, dtheta_dt])

        return f

    # --------------------------------------------------------------------- step
    def step(self, dt: float, voltage: float, load_torque: float = 0.0) -> tuple[float, float, float]:
        """Advance the simulation by ``dt`` using a fixed RK4 step.

        Args:
            dt: Time step [s] (also the only source of time -- fully deterministic).
            voltage: Applied terminal voltage [V].
            load_torque: External load torque at the OUTPUT shaft [N.m] (opposes
                motion). Reflected to the motor shaft as load_torque/(N*eta).

        Returns:
            (output_position, output_velocity, motor_current).
        """
        p = self.params
        voltage = float(np.clip(voltage, -24.0, 24.0))

        # Reflect the output-side load torque to the motor shaft.
        load_torque_motor = load_torque / (p.gear_ratio * p.gear_efficiency)

        x0 = np.array([self.current, self._omega_m, self._theta_m])
        f = self._state_derivative(voltage, load_torque_motor)

        # Stiction guard: if the joint is held static and stays below break-away
        # after the step's applied torque, freeze omega/theta to avoid creep.
        tau_em0 = p.torque_constant * self.current
        stuck_before = is_stuck(self._omega_m, tau_em0 - load_torque_motor, p.friction_params())

        x1 = rk4_step(f, x0, dt)

        # Clamp current to the achievable torque envelope.
        i_lim = self._current_limit()
        self.current = float(np.clip(x1[_I], -i_lim, i_lim))

        new_omega = x1[_W]
        # Enforce the stiction band: if we were stuck and the applied torque is
        # still below break-away, the joint must not have moved.
        if stuck_before and is_stuck(0.0, tau_em0 - load_torque_motor, p.friction_params()):
            new_omega = 0.0
            new_theta = self._theta_m
        else:
            new_theta = x1[_TH]

        w_lim = self._motor_speed_limit()
        self._omega_m = float(np.clip(new_omega, -w_lim, w_lim))
        self._theta_m = float(new_theta)

        # Output-side exposed quantities (gearbox reduction).
        self.velocity = self._omega_m / p.gear_ratio
        self.position = self._theta_m / p.gear_ratio

        # Thermal model (Euler is fine: slow first-order thermal dynamics).
        copper_loss = self.current ** 2 * p.resistance
        output_torque = self.output_torque()
        mechanical_loss = abs(output_torque * self.velocity) * (1.0 - p.gear_efficiency)
        total_loss = copper_loss + mechanical_loss
        dtemp_dt = (
            total_loss - (self.temperature - p.ambient_temp) / p.thermal_resistance
        ) / p.thermal_mass
        self.temperature = float(
            np.clip(self.temperature + dtemp_dt * dt, p.ambient_temp, p.max_temp)
        )

        self._sim_time += dt
        return self.position, self.velocity, self.current

    # ------------------------------------------------------------------ getters
    def motor_torque(self) -> float:
        """Electromagnetic torque at the motor shaft [N.m]."""
        return self.current * self.params.torque_constant

    def output_torque(self) -> float:
        """Torque delivered at the output shaft after the gearbox [N.m]."""
        return self.motor_torque() * self.params.gear_ratio * self.params.gear_efficiency

    def reflected_inertia(self, output_inertia: float) -> float:
        """Inertia of an output-side load reflected to the motor shaft.

        J_reflected = J_out / N**2  (standard reflected-inertia relationship).
        """
        return output_inertia / (self.params.gear_ratio ** 2)

    def effective_output_back_emf_constant(self) -> float:
        """Back-EMF constant referred to the OUTPUT shaft = Ke * N.

        Back-EMF is set by motor speed (Ke * omega_m); since omega_m = N * omega_out,
        the constant seen from the output scales up by the gear ratio.
        """
        return self.params.ke * self.params.gear_ratio

    def get_state(self) -> dict:
        """Output-side state snapshot."""
        return {
            "position": self.position,
            "velocity": self.velocity,
            "current": self.current,
            "torque": self.output_torque(),
            "motor_velocity": self._omega_m,
            "temperature": self.temperature,
            "time": self._sim_time,
        }

    def get_temperature(self) -> float:
        return self.temperature

    def get_efficiency(self) -> float:
        """Mechanical-output / electrical-input power ratio."""
        input_power = abs(self.current * self.params.torque_constant * self._omega_m)
        if input_power < 1e-6:
            return 1.0
        output_power = abs(self.output_torque() * self.velocity)
        return output_power / input_power

    def get_power_loss(self) -> float:
        copper_loss = self.current ** 2 * self.params.resistance
        mechanical_loss = abs(self.output_torque() * self.velocity) * (
            1.0 - self.params.gear_efficiency
        )
        return copper_loss + mechanical_loss

    def reset(self) -> None:
        """Reset all state to initial conditions."""
        self.position = 0.0
        self.velocity = 0.0
        self.current = 0.0
        self._theta_m = 0.0
        self._omega_m = 0.0
        self.temperature = self.params.ambient_temp
        self._sim_time = 0.0


class MotorController:
    """Backward-compatible single-loop PID with correct back-calculation anti-windup.

    Retained so existing call sites keep working; new code should prefer
    :class:`robot_testbench.control.CascadeController`. This implementation fixes
    the two bugs in the original: derivative is taken on the *measurement* with a
    first-order filter (not the raw error), and anti-windup uses proper
    back-calculation (integral correction = (u_sat - u_unsat)/Tt), not the broken
    ``(u_clip - u)/Ki`` term.
    """

    def __init__(
        self,
        gains: PIDGains,
        control_mode: str = "position",
        output_limits: tuple = (-48.0, 48.0),
        tracking_time_constant: float = 0.1,
        derivative_filter_tau: float = 0.01,
    ):
        self.kp = gains.kp
        self.ki = gains.ki
        self.kd = gains.kd
        self.control_mode = control_mode
        self.output_limits = output_limits
        self.tt = tracking_time_constant
        self.deriv_tau = derivative_filter_tau
        self.setpoint = 0.0
        self.integral = 0.0
        self.error = 0.0
        self._prev_measurement = 0.0
        self._deriv_filtered = 0.0
        self._initialized = False

    def set_setpoint(self, setpoint: float):
        self.setpoint = setpoint

    def reset(self):
        self.integral = 0.0
        self.error = 0.0
        self._prev_measurement = 0.0
        self._deriv_filtered = 0.0
        self._initialized = False

    def compute(self, measurement: float, dt: float) -> float:
        self.error = self.setpoint - measurement

        if not self._initialized:
            self._prev_measurement = measurement
            self._initialized = True

        # Derivative on measurement (negated), first-order low-pass filtered.
        if dt > 0:
            raw_deriv = -(measurement - self._prev_measurement) / dt
            alpha = dt / (self.deriv_tau + dt)
            self._deriv_filtered += alpha * (raw_deriv - self._deriv_filtered)
        d_term = self.kd * self._deriv_filtered
        self._prev_measurement = measurement

        u_unsat = self.kp * self.error + self.ki * self.integral + d_term
        u_sat = float(np.clip(u_unsat, *self.output_limits))

        # Back-calculation anti-windup.
        if self.ki != 0.0 and dt > 0:
            self.integral += self.error * dt + (dt / self.tt) * (u_sat - u_unsat) / self.ki

        return u_sat

    def get_error(self) -> float:
        return self.error
